name: deployment-production

on:
  push:
    branches: [ main ]

jobs:
  deployment-production:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Copy updated files
        uses: appleboy/scp-action@v0.1.3
        with:
          password: ${{ secrets.SSH_PRIVATE_PASS_PROD }}
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          source: ./
          target: ~/www/app

      - name: Rebuild project
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PRIVATE_PASS_PROD }}
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USER_PROD }}
          port: 22
          command_timeout: 10m
          script: |
            docker compose --env-file ~/www/.env -f  ~/www/app/docker-compose.yml up -d --build
